mydb:
    url: jdbc:mysql://127.0.0.1:3306/testdb?characterEncoding=utf-8&autoReconnect=true&autoReconnectForPools=true&serverTimezone=GMT%2B8&allowMultiQueries=true
    username: root
    password: root

spring:
    dubbo:
        application:
            name: io3x-dubbo-app
        registry:
          address: zookeeper://192.168.0.105:2181
        protocol:
           name: dubbo

        # 生产者配置
        server: false

        #消费者配置
        consumer:
          check: false
        reference:
          loadbalance: roundrobin #轮询机制
          #loadbalance: random #随机机制
          #loadbalance: leastactive #最少活跃调用数机制

dubbo:
    application:
        name: io3x-dubbo-app
    registry:
      address: zookeeper://192.168.0.105:2181
    protocol:
       name: dubbo

    # 生产者配置
    server: false

    #消费者配置
    consumer:
      check: false
    reference:
      loadbalance: roundrobin #轮询机制
      #loadbalance: random #随机机制
      #loadbalance: leastactive #最少活跃调用数机制