# Tomcat
server:
    tomcat:
        uri-encoding: UTF-8
        max-threads: 1000
        min-spare-threads: 30
    port: 10388
    connection-timeout: 5000ms
    servlet:
        context-path: /

debug: false

spring:
    profiles:
        active: "@profile.active@" #此处由maven的环境选择决定，参考：https://www.jianshu.com/p/b7c75b0c364c
    # jackson时间格式化
    jackson:
        time-zone: GMT+8
        date-format: yyyy-MM-dd HH:mm
    servlet:
        multipart:
            max-file-size: 100MB
            max-request-size: 100MB
            enabled: true
    mvc:
        #throw-exception-if-no-handler-found: true
        static-path-pattern: /static/**

    freemarker:
      suffix: .html
      content-type: text/html
      charset: UTF-8
      cache: false
      template-loader-path: classpath:/templates
      enabled: true

